### ISSUE TITLE
 Unable to register route on existing local domain

### ISSUE THREAD

**Issue by dm-s** [iNPUTmice/p2#19]
after bulding app got this error in console:

Reading configuration from /etc/p2/config.json
OUT (null): <?xml version="1.0" encoding="UTF-8"?><stream:stream xmlns="jabber:c                        omponent:accept" xmlns:stream="http://etherx.jabber.org/streams" to="urlk.org" v                        ersion="1.0" xml:lang="en-GB">
IN  (7947541217090195413): <?xml version="1.0" encoding="UTF-8" standalone="no"?                        ><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:co                        mponent:accept" from="urlk.org" id="7947541217090195413" xml:lang="en-GB">
IN  (7947541217090195413): <stream:error><conflict xmlns="urn:ietf:params:xml:ns                        :xmpp-streams"></conflict><text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml:                        lang="en">Unable to register route on existing local domain</text></stream:error                        >
OUT (7947541217090195413): </stream:stream>
IN  (7947541217090195413): </stream:stream>
conflict
        Unable to register route on existing local domain
OUT (null): <?xml version="1.0" encoding="UTF-8"?><stream:stream xmlns="jabber:c                        omponent:accept" xmlns:stream="http://etherx.jabber.org/streams" to="urlk.org" v                        ersion="1.0" xml:lang="en-GB">
IN  (16874164747661694938): <?xml version="1.0" encoding="UTF-8" standalone="no"                        ?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:c                        omponent:accept" from="urlk.org" id="16874164747661694938" xml:lang="en-GB">
IN  (16874164747661694938): <stream:error><conflict xmlns="urn:ietf:params:xml:n                        s:xmpp-streams"></conflict><text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml                        :lang="en">Unable to register route on existing local domain</text></stream:erro                        r>
OUT (16874164747661694938): </stream:stream>
IN  (16874164747661694938): </stream:stream>
conflict
        Unable to register route on existing local domain
OUT (null): <?xml version="1.0" encoding="UTF-8"?><stream:stream xmlns="jabber:c                        omponent:accept" xmlns:stream="http://etherx.jabber.org/streams" to="urlk.org" v                        ersion="1.0" xml:lang="en-GB">
IN  (4782586016994978799): <?xml version="1.0" encoding="UTF-8" standalone="no"?                        ><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:co                        mponent:accept" from="urlk.org" id="4782586016994978799" xml:lang="en-GB">
OUT (4782586016994978799): </stream:stream>
IN  (4782586016994978799): <stream:error><conflict xmlns="urn:ietf:params:xml:ns                        :xmpp-streams"></conflict><text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml:                        lang="en">Unable to register route on existing local domain</text></stream:error                        >
IN  (4782586016994978799): </stream:stream>
Exception in thread "main" java.lang.NullPointerException
        at rocks.xmpp.extensions.component.accept.ExternalComponent.connect(Exte                        rnalComponent.java:132)
        at rocks.xmpp.core.session.XmppSession.connect(XmppSession.java:315)
        at eu.siacs.p2.P2.connectAndKeepRetrying(P2.java:86)
        at eu.siacs.p2.P2.main(P2.java:80)
        at eu.siacs.p2.P2.main(P2.java:38)

**Comment by dm-s** [comment]
I'm using debian 10. The version of java:

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing).

Cause of version of java (not java 8), i'm ought to add some additional dependences. without this dependencies i can't compile. 
[pom.zip](https://github.com/iNPUTmice/p2/files/4786076/pom.zip)
